# permissions for end users to edit googlecasclusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: googlecasclusterissuer-editor-role
rules:
- apiGroups:
  - cas-issuer.jetstack.io
  resources:
  - googlecasclusterissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cas-issuer.jetstack.io
  resources:
  - googlecasclusterissuers/status
  verbs:
  - get
