# permissions for end users to view googlecasclusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: googlecasclusterissuer-viewer-role
rules:
- apiGroups:
  - cas-issuer.jetstack.io
  resources:
  - googlecasclusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cas-issuer.jetstack.io
  resources:
  - googlecasclusterissuers/status
  verbs:
  - get
