# permissions for end users to view googlecasissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: googlecasissuer-viewer-role
rules:
- apiGroups:
  - cas-issuer.jetstack.io
  resources:
  - googlecasissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cas-issuer.jetstack.io
  resources:
  - googlecasissuers/status
  verbs:
  - get
