name: tests
on: [pull_request, push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: install kubebuilder
        run: |
          os=$(go env GOOS)
          arch=$(go env GOARCH)
          curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/
          sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
          export PATH=$PATH:/usr/local/kubebuilder/bin
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run unit tests
        run: make test
      -
        name: Run e2e tests
        run: make e2e
        env:
          AGE_SECRET_KEY: ${{ secrets.AGE_SECRET_KEY }}
