name: tests
on: [pull_request, push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    container: golang:1.15
    steps:
      - name: install kubebuilder
        run: |
          os=$(go env GOOS)
          arch=$(go env GOARCH)
          curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/
          mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
          export PATH=$PATH:/usr/local/kubebuilder/bin
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run tests
        run: make test